-- Create migration_lock.toml if not exists
-- This file is automatically generated by Prisma

-- migration.sql
-- M3: Add partial unique index for bookings (Rule 2)
-- This replaces the standard @@unique with a partial index that excludes cancelled/completed rows

-- Drop the existing unique index if it exists
DROP INDEX IF EXISTS "bookings_doctorId_bookingDate_startTime_key";

-- Create partial unique index: only active bookings block the slot
CREATE UNIQUE INDEX "unique_doctor_slot_active"
ON "bookings" ("doctor_id", "booking_date", "start_time")
WHERE "status" IN ('CONFIRMED', 'RESCHEDULED');

-- Verify the index was created
-- SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'bookings';